export const LOGIN_SUCCESSED = "LOGIN_SUCCESSED";
export const GET_TOP_NEW_COURSE_SUCCESSED = "GET_TOP_NEW_COURSE_SUCCESSED";
export const GET_TODOS = "GET_TODOS";
export const GET_CURRENT_TODO = "GET_CURRENT_TODO";
