export const LOGIN_SUCCESSED = "LOGIN_SUCCESSED";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REGISTER_SUCCESSED = "REGISTER_SUCCESSED";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const SEND_EMAIL_SUCCESSED="SEND_EMAIL_SUCCESSED";
export const SEND_EMAIL_FAILED="SEND_EMAIL_FAILED";
export const CONFIRM_OTP_EMAIL_SUCCESSED="CONFIRM_OTP_EMAIL_SUCCESSED";
export const CONFIRM_OTP_EMAIL_FAILED="CONFIRM_OTP_EMAIL_FAILED";
export const GET_USERINFO_SUCCESSED="GET_USERINFO_SUCCESSED";
export const GET_USERINFO_FAILED="GET_USERINFO_FAILED";


export const GET_TOP_NEW_COURSE_SUCCESSED = "GET_TOP_NEW_COURSE_SUCCESSED";
