export const LOGIN_SUCCESSED = "LOGIN_SUCCESSED";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REGISTER_SUCCESSED = "REGISTER_SUCCESSED";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const SEND_EMAIL_SUCCESSED = "SEND_EMAIL_SUCCESSED";
export const SEND_EMAIL_FAILED = "SEND_EMAIL_FAILED";
export const CONFIRM_OTP_EMAIL_SUCCESSED = "CONFIRM_OTP_EMAIL_SUCCESSED";
export const CONFIRM_OTP_EMAIL_FAILED = "CONFIRM_OTP_EMAIL_FAILED";
export const GET_USERINFO_SUCCESSED = "GET_USERINFO_SUCCESSED";
export const GET_USERINFO_FAILED = "GET_USERINFO_FAILED";
export const FORGET_PASSWORD_SEND_EMAIL_SUCCESSED =
  "FORGET_PASSWORD_SEND_EMAIL_SUCCESSED";
export const FORGET_PASSWORD_SEND_EMAIL_FAILED =
  "FORGET_PASSWORD_SEND_EMAIL_FAILED";
export const FORGET_PASSWORD_UPDATE_NEW_PASSWORD_SUCCESSED =
  "FORGET_PASSWORD_UPDATE_NEW_PASSWORD_SUCCESSED";
export const FORGET_PASSWORD_UPDATE_NEW_PASSWORD_FAILED =
  "FORGET_PASSWORD_UPDATE_NEW_PASSWORD_FAILED";
export const LOGOUT = "LOGOUT";
export const UPDATE_AVATAR_SUCCESSED="UPDATE_AVATAR_SUCCESSED"
export const UPDATE_AVATAR_FAILED="UPDATE_AVATAR_FAILED"

//account management
export const CHANGE_PASSWORD_SUCCESSED = "CHANGE_PASSWORD_SUCCESSED";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

//course
export const GET_TOP_NEW_COURSE_SUCCESSED = "GET_TOP_NEW_COURSE_SUCCESSED";
export const GET_TOP_NEW_COURSE_FAILED = "GET_TOP_NEW_COURSE_FAILED";
export const GET_TOP_REGISTER_COURSE_SUCCESSED =
  "GET_TOP_REGISTER_COURSE_SUCCESSED";
export const GET_TOP_REGISTER_COURSE_FAILED = "GET_TOP_REGISTER_COURSE_FAILED";
export const GET_TOP_RATE_IN_WEEK_SUCCESSED = "GET_TOP_RATE_IN_WEEK_SUCCESSED";
export const GET_TOP_RATE_IN_WEEK_FAILED = "GET_TOP_RATE_IN_WEEK_FAILED";
export const GET_FAVORITE_COURSES_SUCCSEDD = "GET_FAVORITE_COURSES_SUCCSEDD";
export const GET_FAVORITE_COURSES_FAILED = "GET_FAVORITE_COURSES_FAILED";
export const GET_COURSE_DETAIL_SUCCSED = "GET_COURSE_DETAIL_SUCCSED";
export const GET_COURSE_DETAIL_FAILED = "GET_COURSE_DETAIL_FAILED";
export const ADD_FAVORITE_COURSE_SUCCESSED = "ADD_FAVORITE_COURSE_SUCCESSED";
export const ADD_FAVORITE_COURSE_FAILED = "ADD_FAVORITE_COURSE_FAILED";
export const REMOVE_FAVORITE_COURSE_SUCCESSED =
  "REMOVE_FAVORITE_COURSE_SUCCESSED";
export const REMOVE_FAVORITE_COURSE_FAILED = "REMOVE_FAVORITE_COURSE_FAILED";
export const ADD_COURSE_TO_CART_SUCCESSED = "ADD_COURSE_TO_CART_SUCCESSED";
export const ADD_COURSE_TO_CART_FAILED = "ADD_COURSE_TO_CART_FAILED";
export const REMOVE_COURSE_FROM_CART_SUCCESSED =
  "REMOVE_COURSE_FROM_CART_SUCCESSED";
export const REMOVE_COURSE_FROM_CART_FAILED = "REMOVE_COURSE_FROM_CART_FAILED";
export const GET_COURSES_FROM_CART_SUCCESSED = "GET_COURSES_FROM_CART_SUCCESSED";
export const GET_COURSES_FROM_CART_FAILED = "GET_COURSES_FROM_CART_FAILED";
export const GET_COURSES_FROM_DASHBOARD_SUCCESSED = "GET_COURSES_FROM_DASHBOARD_SUCCESSED";
export const GET_COURSES_FROM_DASHBOARD_FAILED = "GET_COURSES_FROM_DASHBOARD_FAILED";
export const SEARCH_COURSES_SUCCESSED="SEARCH_COURSES_SUCCESSED"
export const SEARCH_COURSES_FAILED="SEARCH_COURSES_FAILED"
export const CHARGE_COURSE_SUCCESSED="CHARGE_COURSE_SUCCESSED"
export const CHARGE_COURSE_FAILED="CHARGE_COURSE_FAILED"
export const SORT_COURSES_BY_ASC_SUCCESSED="SORT_COURSES_BY_ASC_SUCCESSED"
export const SORT_COURSES_BY_ASC_FAILED="SORT_COURSES_BY_ASC_SUCCESSED"
export const SORT_COURSES_BY_DESC_SUCCESSED="SORT_COURSES_BY_DESC_SUCCESSED"
export const SORT_COURSES_BY_DESC_FAILED="SORT_COURSES_BY_DESC_FAILED"

//category
export const GET_CATEGORIES_SUCCESSED = "GET_CATEGORIES_SUCCESSED";
export const GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED";
export const GET_CATEGORY_DETAIL_SUCCESSED="GET_CATEGORY_DETAIL_SUCCESSED"
export const GET_CATEGORY_DETAIL_FAILED="GET_CATEGORY_DETAIL_FAILED"

//rate
export const RATE_COURSE_SUCCESSED="RATE_COURSE_SUCCESSED"
export const RATE_COURSE_FAILED="RATE_COURSE_FAILED"
export const GET_RATES_COURSE_SUCCESSED="GET_RATES_COURSE_SUCCESSED"
export const GET_RATES_COURSE_FAILED="GET_RATES_COURSE_FAILED"

//search
export const GET_SEARCH_TOP_COURSES_SUCCESSED="GET_SEARCH_TOP_COURSES_SUCCESSED"
export const GET_SEARCH_TOP_COURSES_FAILED="GET_SEARCH_TOP_COURSES_FAILED"